/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace ContextRegistry {
  export type ContextEntryStruct = {
    contentHash: BytesLike;
    metadataURI: string;
    registeredBy: AddressLike;
    registeredAt: BigNumberish;
    bucketTokenId: BigNumberish;
    sourceType: string;
    revoked: boolean;
  };

  export type ContextEntryStructOutput = [
    contentHash: string,
    metadataURI: string,
    registeredBy: string,
    registeredAt: bigint,
    bucketTokenId: bigint,
    sourceType: string,
    revoked: boolean
  ] & {
    contentHash: string;
    metadataURI: string;
    registeredBy: string;
    registeredAt: bigint;
    bucketTokenId: bigint;
    sourceType: string;
    revoked: boolean;
  };
}

export interface ContextRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_ADMIN_ROLE"
      | "REGISTRAR_ROLE"
      | "bucketContexts"
      | "contexts"
      | "getBucketContextCount"
      | "getBucketContextIds"
      | "getContext"
      | "getProvenanceByHash"
      | "getRoleAdmin"
      | "grantRole"
      | "hasRole"
      | "hashToContext"
      | "memoryNFT"
      | "registerContext"
      | "renounceRole"
      | "revokeContext"
      | "revokeRole"
      | "supportsInterface"
      | "totalRegistered"
      | "updateContextMetadata"
      | "verifyContent"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ContextMetadataUpdated"
      | "ContextRegistered"
      | "ContextRevoked"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REGISTRAR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "bucketContexts",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "contexts", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getBucketContextCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBucketContextIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getContext",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getProvenanceByHash",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hashToContext",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "memoryNFT", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerContext",
    values: [BytesLike, BigNumberish, BytesLike, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeContext",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalRegistered",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateContextMetadata",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyContent",
    values: [BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REGISTRAR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bucketContexts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "contexts", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getBucketContextCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBucketContextIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getContext", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getProvenanceByHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hashToContext",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "memoryNFT", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerContext",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeContext",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalRegistered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateContextMetadata",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyContent",
    data: BytesLike
  ): Result;
}

export namespace ContextMetadataUpdatedEvent {
  export type InputTuple = [
    contextId: BytesLike,
    oldURI: string,
    newURI: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    contextId: string,
    oldURI: string,
    newURI: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    contextId: string;
    oldURI: string;
    newURI: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ContextRegisteredEvent {
  export type InputTuple = [
    contextId: BytesLike,
    bucketTokenId: BigNumberish,
    contentHash: BytesLike,
    sourceType: string,
    metadataURI: string,
    registeredBy: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    contextId: string,
    bucketTokenId: bigint,
    contentHash: string,
    sourceType: string,
    metadataURI: string,
    registeredBy: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    contextId: string;
    bucketTokenId: bigint;
    contentHash: string;
    sourceType: string;
    metadataURI: string;
    registeredBy: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ContextRevokedEvent {
  export type InputTuple = [
    contextId: BytesLike,
    bucketTokenId: BigNumberish,
    revokedBy: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    contextId: string,
    bucketTokenId: bigint,
    revokedBy: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    contextId: string;
    bucketTokenId: bigint;
    revokedBy: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ContextRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): ContextRegistry;
  waitForDeployment(): Promise<this>;

  interface: ContextRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  REGISTRAR_ROLE: TypedContractMethod<[], [string], "view">;

  bucketContexts: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;

  contexts: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, bigint, bigint, string, boolean] & {
        contentHash: string;
        metadataURI: string;
        registeredBy: string;
        registeredAt: bigint;
        bucketTokenId: bigint;
        sourceType: string;
        revoked: boolean;
      }
    ],
    "view"
  >;

  getBucketContextCount: TypedContractMethod<
    [bucketTokenId: BigNumberish],
    [bigint],
    "view"
  >;

  getBucketContextIds: TypedContractMethod<
    [bucketTokenId: BigNumberish],
    [string[]],
    "view"
  >;

  getContext: TypedContractMethod<
    [contextId: BytesLike],
    [ContextRegistry.ContextEntryStructOutput],
    "view"
  >;

  getProvenanceByHash: TypedContractMethod<
    [contentHash: BytesLike],
    [
      [string, bigint, string, bigint] & {
        contextId: string;
        registeredAt: bigint;
        registeredBy: string;
        bucketTokenId: bigint;
      }
    ],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  hashToContext: TypedContractMethod<[arg0: BytesLike], [string], "view">;

  memoryNFT: TypedContractMethod<[], [string], "view">;

  registerContext: TypedContractMethod<
    [
      contextId: BytesLike,
      bucketTokenId: BigNumberish,
      contentHash: BytesLike,
      sourceType: string,
      metadataURI: string
    ],
    [void],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeContext: TypedContractMethod<
    [contextId: BytesLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  totalRegistered: TypedContractMethod<[], [bigint], "view">;

  updateContextMetadata: TypedContractMethod<
    [contextId: BytesLike, newURI: string],
    [void],
    "nonpayable"
  >;

  verifyContent: TypedContractMethod<
    [contextId: BytesLike, contentHash: BytesLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "REGISTRAR_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "bucketContexts"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "contexts"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, bigint, bigint, string, boolean] & {
        contentHash: string;
        metadataURI: string;
        registeredBy: string;
        registeredAt: bigint;
        bucketTokenId: bigint;
        sourceType: string;
        revoked: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getBucketContextCount"
  ): TypedContractMethod<[bucketTokenId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getBucketContextIds"
  ): TypedContractMethod<[bucketTokenId: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "getContext"
  ): TypedContractMethod<
    [contextId: BytesLike],
    [ContextRegistry.ContextEntryStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProvenanceByHash"
  ): TypedContractMethod<
    [contentHash: BytesLike],
    [
      [string, bigint, string, bigint] & {
        contextId: string;
        registeredAt: bigint;
        registeredBy: string;
        bucketTokenId: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "hashToContext"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "memoryNFT"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerContext"
  ): TypedContractMethod<
    [
      contextId: BytesLike,
      bucketTokenId: BigNumberish,
      contentHash: BytesLike,
      sourceType: string,
      metadataURI: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeContext"
  ): TypedContractMethod<[contextId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "totalRegistered"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "updateContextMetadata"
  ): TypedContractMethod<
    [contextId: BytesLike, newURI: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyContent"
  ): TypedContractMethod<
    [contextId: BytesLike, contentHash: BytesLike],
    [boolean],
    "view"
  >;

  getEvent(
    key: "ContextMetadataUpdated"
  ): TypedContractEvent<
    ContextMetadataUpdatedEvent.InputTuple,
    ContextMetadataUpdatedEvent.OutputTuple,
    ContextMetadataUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ContextRegistered"
  ): TypedContractEvent<
    ContextRegisteredEvent.InputTuple,
    ContextRegisteredEvent.OutputTuple,
    ContextRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "ContextRevoked"
  ): TypedContractEvent<
    ContextRevokedEvent.InputTuple,
    ContextRevokedEvent.OutputTuple,
    ContextRevokedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;

  filters: {
    "ContextMetadataUpdated(bytes16,string,string,uint256)": TypedContractEvent<
      ContextMetadataUpdatedEvent.InputTuple,
      ContextMetadataUpdatedEvent.OutputTuple,
      ContextMetadataUpdatedEvent.OutputObject
    >;
    ContextMetadataUpdated: TypedContractEvent<
      ContextMetadataUpdatedEvent.InputTuple,
      ContextMetadataUpdatedEvent.OutputTuple,
      ContextMetadataUpdatedEvent.OutputObject
    >;

    "ContextRegistered(bytes16,uint256,bytes32,string,string,address,uint256)": TypedContractEvent<
      ContextRegisteredEvent.InputTuple,
      ContextRegisteredEvent.OutputTuple,
      ContextRegisteredEvent.OutputObject
    >;
    ContextRegistered: TypedContractEvent<
      ContextRegisteredEvent.InputTuple,
      ContextRegisteredEvent.OutputTuple,
      ContextRegisteredEvent.OutputObject
    >;

    "ContextRevoked(bytes16,uint256,address,uint256)": TypedContractEvent<
      ContextRevokedEvent.InputTuple,
      ContextRevokedEvent.OutputTuple,
      ContextRevokedEvent.OutputObject
    >;
    ContextRevoked: TypedContractEvent<
      ContextRevokedEvent.InputTuple,
      ContextRevokedEvent.OutputTuple,
      ContextRevokedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
  };
}
